services:
  - type: web
    name: nexus-hrm-api
    env: node
    plan: free
    buildCommand: "cd server && sed -i 's/provider = \"sqlite\"/provider = \"postgresql\"/g' prisma/schema.prisma && npm install && npx prisma generate && npx prisma db push --accept-data-loss"
    startCommand: "cd server && npm start"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: "https://nexus-hrm.web.app"
      - key: NODE_ENV
        value: "production"
