-- AlterTable
ALTER TABLE "AuditLog" ADD COLUMN     "ipAddress" TEXT;

-- AlterTable
ALTER TABLE "LeaveRequest" ADD COLUMN     "leaveDays" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "leaveAccruedAt" TIMESTAMP(3),
ADD COLUMN     "leaveAllowance" DOUBLE PRECISION NOT NULL DEFAULT 24,
ADD COLUMN     "leaveBalance" DOUBLE PRECISION NOT NULL DEFAULT 0;
